#ifndef SIGVERSE_MIRROR_THERAPY_GUI_GUI_MAIN_FRAME
#define SIGVERSE_MIRROR_THERAPY_GUI_GUI_MAIN_FRAME

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include <sigverse/tools/LinkageGraspGUI/gui/LinkageGraspGUIFrame.h>
#include <sigverse/tools/LinkageGraspGUI/AvatarController.h>

#include <wx/wxprec.h>
#include <wx/cmdline.h>

//// end generated include

/** Implementing MainFrame */
class LinkageGraspGUIMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnMainFrameClose( wxCloseEvent& event );
		void OnLinkageGraspClick( wxCommandEvent& event );
		void OnReverseModeChoice( wxCommandEvent& event );
		void OnLongArmClick( wxCommandEvent& event );
		void OnShortArmClick( wxCommandEvent& event );
		void OnRobotArmClick( wxCommandEvent& event );

		AvatarController avatarController;

	public:
		/** Constructor */
		LinkageGraspGUIMainFrame( wxWindow* parent, const int argc, const wxArrayString &argv );
	//// end generated class members
	
};

#endif // SIGVERSE_MIRROR_THERAPY_GUI_GUI_MAIN_FRAME
