/*
 * Send message to LinkageGrasp controller in order to control avatar of SIGVerse.
 *
 * <Arguments>
 *   1:IP address for connect to SIGVerse.
 *   2:Port number for connect to SIGVerse.
 * 
 * <Notice>
 * - Parameter file name is LinkageGrasp.ini.
 * - The design of this GUI was made by wxFormBuilder.
 *     (Basically, LinkageGraspGUI.h and LinkageGraspGUI.cpp were generated by wxFormBuilder in automatically.)
 */
#include <sigverse/tools/LinkageGraspGUI/Param.h>
#include <sigverse/tools/LinkageGraspGUI/gui/LinkageGraspGUIMainFrame.h>

#ifdef __BORLANDC__
	#pragma hdrstop
#endif

const std::string Param::PARAM_FILE_NAME = "LinkageGraspGUI.ini";

std::string Param::sigServiceName;


/*
 * Main class
 */
class MainApp : public wxApp
{
private :

public:
	bool OnInit();

	void OnInitCmdLine(wxCmdLineParser &parser);
	bool OnCmdLineParsed(wxCmdLineParser &parser);
};


IMPLEMENT_APP( MainApp )


/*
 * Initialize this class.
 */
bool MainApp::OnInit()
{
	if ( !wxApp::OnInit() ){ return false; }


	LinkageGraspGUIMainFrame *frame = new LinkageGraspGUIMainFrame(NULL, wxGetApp().argc, wxGetApp().argv.GetArguments());
	
	frame->Show();

	return true;
}

/*
 * Initialize command line args.
 */
void MainApp::OnInitCmdLine(wxCmdLineParser &parser)
{
	wxCmdLineEntryDesc g_cmdLineDesc [] =
	{
		{ wxCMD_LINE_PARAM,  NULL, NULL, NULL, wxCMD_LINE_VAL_STRING, wxCMD_LINE_PARAM_MULTIPLE },
		{ wxCMD_LINE_NONE }
	};

	parser.SetDesc(g_cmdLineDesc);
}


bool MainApp::OnCmdLineParsed(wxCmdLineParser &parser)
{
	return true;
}
