#ifndef SIGVERSE_ImitationMotionAccumulatorGUIMainFrame
#define SIGVERSE_ImitationMotionAccumulatorGUIMainFrame

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include <sigverse/tools/ImitationMotionAccumulatorGUI/AvatarController.h>
#include "ImitationMotionAccumulatorGUIFrame.h"

#include <wx/wxprec.h>
#include <wx/cmdline.h>

//// end generated include

/** Implementing MainFrame */
class ImitationMotionAccumulatorGUIMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnMainFrameClose( wxCloseEvent& event );
		void OnMirrorMirrorTherapyClick( wxCommandEvent& event );
		void OnMirrorLongArmClick( wxCommandEvent& event );
		void OnMirrorShortArmClick( wxCommandEvent& event );
		void OnMirrorRobotArmClick( wxCommandEvent& event );
		void OnLinkageChangeClick( wxCommandEvent& event );
		void OnSosMiddleArmClick( wxCommandEvent& event );
		void OnSosLongArmClick( wxCommandEvent& event );
		void OnSosShortArmClick( wxCommandEvent& event );
		void OnSosAddDeskHeightClick( wxCommandEvent& event );
		void OnSosAddPlatePositionClick( wxCommandEvent& event );

		AvatarController avatarController;
	public:
		/** Constructor */
		ImitationMotionAccumulatorGUIMainFrame( wxWindow* parent, const int argc, const wxArrayString &argv );
	//// end generated class members
};

#endif // SIGVERSE_ImitationMotionAccumulatorGUIMainFrame
