#ifndef __ImitationMotionAccumulatorGUIMainFrame__
#define __ImitationMotionAccumulatorGUIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "ImitationMotionAccumulatorGUIFrame.h"

#include <wx/wxprec.h>
#include <wx/cmdline.h>

//// end generated include

/** Implementing MainFrame */
class ImitationMotionAccumulatorGUIMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnMainFrameClose( wxCloseEvent& event );
		void OnMirrorMirrorTherapyClick( wxCommandEvent& event );
		void OnImitationModeSelect( wxCommandEvent& event );
	public:
		/** Constructor */
		ImitationMotionAccumulatorGUIMainFrame( wxWindow* parent, const int argc, const wxArrayString &argv );

	//// end generated class members
	
};

#endif // __ImitationMotionAccumulatorGUIMainFrame__
